<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="4" ignored="0" total="5" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-12-28T11:23:52 IST" name="Default suite" finished-at="2021-12-28T11:26:33 IST" duration-ms="161260">
    <groups>
      <group name="smokeSuite">
        <method signature="TestNGCreateContact.CreatingContactTest()[pri:0, instance:practise.TestNGCreateContact@636be97c]" name="CreatingContactTest" class="practise.TestNGCreateContact"/>
      </group> <!-- smokeSuite -->
    </groups>
    <test started-at="2021-12-28T11:23:52 IST" name="Default test" finished-at="2021-12-28T11:26:33 IST" duration-ms="161260">
      <class name="practise.TestNGCreateContact">
        <test-method is-config="true" signature="connectToDataBase()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:23:52 IST" name="connectToDataBase" finished-at="2021-12-28T11:23:52 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- connectToDataBase -->
        <test-method is-config="true" signature="launchingBrowser()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:23:52 IST" name="launchingBrowser" finished-at="2021-12-28T11:24:11 IST" duration-ms="19131" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchingBrowser -->
        <test-method is-config="true" signature="loginToAppl()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:24:11 IST" name="loginToAppl" finished-at="2021-12-28T11:24:25 IST" duration-ms="13705" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAppl -->
        <test-method retried="true" signature="CreatingContactTest()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:24:25 IST" name="CreatingContactTest" finished-at="2021-12-28T11:24:49 IST" duration-ms="24352" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at practise.TestNGCreateContact.CreatingContactTest(TestNGCreateContact.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreatingContactTest -->
        <test-method is-config="true" signature="logoutOfAppl()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:24:49 IST" name="logoutOfAppl" finished-at="2021-12-28T11:24:51 IST" duration-ms="2257" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutOfAppl -->
        <test-method is-config="true" signature="loginToAppl()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:24:51 IST" name="loginToAppl" finished-at="2021-12-28T11:24:54 IST" duration-ms="2334" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAppl -->
        <test-method retried="true" signature="CreatingContactTest()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:24:54 IST" name="CreatingContactTest" finished-at="2021-12-28T11:25:03 IST" duration-ms="9044" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at practise.TestNGCreateContact.CreatingContactTest(TestNGCreateContact.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreatingContactTest -->
        <test-method is-config="true" signature="logoutOfAppl()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:25:03 IST" name="logoutOfAppl" finished-at="2021-12-28T11:25:04 IST" duration-ms="1173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutOfAppl -->
        <test-method is-config="true" signature="loginToAppl()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:25:04 IST" name="loginToAppl" finished-at="2021-12-28T11:25:06 IST" duration-ms="1930" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAppl -->
        <test-method retried="true" signature="CreatingContactTest()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:25:06 IST" name="CreatingContactTest" finished-at="2021-12-28T11:25:17 IST" duration-ms="10952" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at practise.TestNGCreateContact.CreatingContactTest(TestNGCreateContact.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreatingContactTest -->
        <test-method is-config="true" signature="logoutOfAppl()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:25:17 IST" name="logoutOfAppl" finished-at="2021-12-28T11:25:20 IST" duration-ms="3438" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutOfAppl -->
        <test-method is-config="true" signature="loginToAppl()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:25:20 IST" name="loginToAppl" finished-at="2021-12-28T11:25:27 IST" duration-ms="6348" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAppl -->
        <test-method retried="true" signature="CreatingContactTest()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:25:27 IST" name="CreatingContactTest" finished-at="2021-12-28T11:25:51 IST" duration-ms="24681" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at practise.TestNGCreateContact.CreatingContactTest(TestNGCreateContact.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreatingContactTest -->
        <test-method is-config="true" signature="logoutOfAppl()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:25:51 IST" name="logoutOfAppl" finished-at="2021-12-28T11:25:55 IST" duration-ms="3349" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutOfAppl -->
        <test-method is-config="true" signature="loginToAppl()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:25:55 IST" name="loginToAppl" finished-at="2021-12-28T11:26:02 IST" duration-ms="7512" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAppl -->
        <test-method signature="CreatingContactTest()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:26:02 IST" name="CreatingContactTest" finished-at="2021-12-28T11:26:27 IST" duration-ms="25042" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at practise.TestNGCreateContact.CreatingContactTest(TestNGCreateContact.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreatingContactTest -->
        <test-method is-config="true" signature="logoutOfAppl()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:26:28 IST" name="logoutOfAppl" finished-at="2021-12-28T11:26:31 IST" duration-ms="3470" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutOfAppl -->
        <test-method is-config="true" signature="closingBrowser()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:26:31 IST" name="closingBrowser" finished-at="2021-12-28T11:26:33 IST" duration-ms="1826" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closingBrowser -->
        <test-method is-config="true" signature="closingDataBase()[pri:0, instance:practise.TestNGCreateContact@636be97c]" started-at="2021-12-28T11:26:34 IST" name="closingDataBase" finished-at="2021-12-28T11:26:34 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closingDataBase -->
      </class> <!-- practise.TestNGCreateContact -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
